### ISSUE TITLE
主线第五章缺少选项

### ISSUE THREAD

**Issue by idrawer** [ssz66666/qfzct-66rpg#1]
从港口逃离拿枪威胁康兴的部分没有“不回延安了”的选项，查了攻略自己前面也没选错啊

**Comment by ssz66666** [comment]
请对照攻略[https://www.douban.com/review/7375150/](https://www.douban.com/review/7375150/)"夜总会调查"部分。
未出现“不回延安了”选项应为在该推理部分没有问出橙娘的住处。

**Comment by idrawer** [comment]
多谢指点。推理部分我没看攻略，现在去对照着再走一遍




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sizhe Sun"<notifications@github.com&gt;; 
发送时间: 2020年1月28日(星期二) 凌晨0:00
收件人: "ssz66666/qfzct-66rpg"<qfzct-66rpg@noreply.github.com&gt;; 
抄送: "月上轩而飞光"<albus71352@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ssz66666/qfzct-66rpg] 主线第五章缺少选项 (#1)




请对照攻略https://www.douban.com/review/7375150/"夜总会调查"部分。
 未出现“不回延安了”选项应为在该推理部分没有问出橙娘的住处。
