### ISSUE TITLE
这个仓库里的游戏，是原版的flash版本，还是用html重写过的？

### ISSUE THREAD

**Issue by TurnOffNOD** [ssz66666/qfzct-66rpg#2]
在网页https://ssz66666.github.io/qfzct-66rpg/ 上玩的时候感觉还是有一点卡，这个页面的游戏是原版的flash版本还是说有高人用html重写过了？

**Comment by ssz66666** [comment]
此网页版是调用的橙光自己官方的H5版橙光游戏引擎实现，和下架前直接在橙光官网玩的效果是一样的。

**Comment by TurnOffNOD** [comment]
> 

哦，好的，谢谢回答。
